
apiVersion: v1
kind: Secret
metadata:
    name: mongodb-secret
type: Opaque
data:
    # Base64 encoded values (use `echo -n 'your_value' | base64` to encode)
    # Default values: username: 'username', password: 'password'
    mongo-root-username: dXNlcm5hbWU= 
    mongo-root-password: cGFzc3dvcmQ=